### ISSUE TITLE
Unit tests

### ISSUE THREAD

**Issue by jabhishek** [christianalfoni/webpack-express-boilerplate#10]
Hi,

First of all, thanks for the good work that you have done here. As an added feature, it would be great if you could add unit tests to the boilerplate.

Thanks,
Abhi.

**Comment by jabhishek** [comment]
Hi, inspired by your project, I have created a [react-express boilerplate](https://github.com/jabhishek/react-express-webpack-boilerplate) that uses React-router and have karma/jasmine unit tests. If you are ok with it, I can add them in this repo and do a PR.

**Comment by christianalfoni** [comment]
Hi @jabhishek!

Really good to hear that this has been helpful to you! I wanted to keep testing out of the boilerplate because people or so opinionated by them. But you can make a pull request in the readme pointing to yours? which explains the added features?
