### ISSUE TITLE
running node server in production

### ISSUE THREAD

**Issue by doroncy** [christianalfoni/webpack-express-boilerplate#14]
the current configuration doesn't bundle the nodejs server side code, therefore in order to run the production bundled code you need to run it via babel-node, which is not production ready due to the heavy runtime compiling.
please advice what should be done in order to have this project ready for production? i saw solutions that  created two webpack configuration for frontend and backend and using gulp building both projects,
any other ideas?

**Comment by jabhishek** [comment]
Hi @doroncy, I had the same concerns and I ended up changing my bolierplate to use plain old node code, and not relying on babel to create a bundle. Having said that, I am on node 4.1, which has pretty decent es6 support ([details here](https://nodejs.org/en/blog/release/v4.0.0/))

**Comment by christianalfoni** [comment]
Hi guys, and sorry for late reply.

I did a test on this and I am planning to update the boilerplate. In the meantime, take a look at this: http://jlongster.com/Backend-Apps-with-Webpack--Part-I

**Comment by sohibul** [comment]
also waiting for server side
