### ISSUE TITLE
Question: Reloading express

### ISSUE THREAD

**Issue by daveroberts** [christianalfoni/webpack-express-boilerplate#16]
Is it possible to have express reload when files change?  How would that be incorporated into this workflow?

**Comment by cannap** [comment]
Hi you can do this with nodemon

**Comment by christianalfoni** [comment]
@daveroberts Though you probably want to create a second node instance for your backend. Proxying all API requests through the boilerplate node instance to your actual backend. That way you do not need to rebundle the frontend project everytime node restarts
