### ISSUE TITLE
Upgrading to Babel 6

### ISSUE THREAD

**Issue by jenil** [christianalfoni/webpack-express-boilerplate#17]

**Comment by kbiedrzycki** [comment]
+1

**Comment by jabhishek** [comment]
Upgrading to babel 6 will be an issue as babel 6 isn't supported by babel-plugin-react-transform yet. It's best to wait until the plugin supports babel 6 - you can follow the discussion [here](https://github.com/gaearon/babel-plugin-react-transform/issues/46). Once that is in place, I am happy to take this up and do a PR.

**Comment by christianalfoni** [comment]
@jabhishek I believe this now works. Or maybe still in Beta? I set this up on a different project and it works. But yeah, maybe wait until out of beta

**Comment by jabhishek** [comment]
I have created a pull request [#25](https://github.com/christianalfoni/webpack-express-boilerplate/pull/25) for this. Do let me know if you spot any issues. :-)

**Comment by christianalfoni** [comment]
Merged :-)

**Comment by jabhishek** [comment]
Thanks @christianalfoni for the merge. I couldn't still upgrade my boilerplate as it has a dependency on babel-plugin-rewire, which still has some issues. Should be fixed soon though (hopefully). :-)

**Comment by jenil** [comment]
Awesome! Thanks @jabhishek
