### ISSUE TITLE
Adding server js files to get stuff from database?

### ISSUE THREAD

**Issue by henrikra** [christianalfoni/webpack-express-boilerplate#23]
Hello

Is it possible to add example on how can I add api routes where I can get data from database form example? I tried to add
app.get('/api/lol', function response(req, res) {
  res.write("looooooooooool");
});
to server.js and call it with jQuery
$.get('/api/lol', function(result) {
      console.log(result);
    });
but Im not getting anything back.

**Comment by henrikra** [comment]
I think this has to be something with app.get('*', function response ?

**Comment by christianalfoni** [comment]
That should work, but you have to add it at the top. Right after `const app = express()` :-)

**Comment by henrikra** [comment]
Thank you jesus! It worked :D

**Comment by christianalfoni** [comment]
If you look a bit further down you see a `app.get('*'...`, this one picks up all get requests. Any get routes defines after it will never be checked :-) That is the reason

**Comment by henrikra** [comment]
Thank you for explanation!
