### ISSUE TITLE
Using fat arrows?

### ISSUE THREAD

**Issue by henrikra** [christianalfoni/webpack-express-boilerplate#24]
With this boiler plate when Im using fat arrow function they are not working. Seems like babel is not transformin them to es5. I have tried to edit babelrc file with no luck. Can somebody confirm this or is it just my issue?

**Comment by christianalfoni** [comment]
You have an example of how you are using them?

**Comment by henrikra** [comment]
Sorry I accidently put the fat arrow to wrong place. So nothing wrong with babel setup :)
