### ISSUE TITLE
Add basic deployment instructions to Readme 

### ISSUE THREAD

**Issue by Kadrian** [christianalfoni/webpack-express-boilerplate#26]
Hi, I was wondering how you run the server in production? Something like this?

`node server.js NODE_ENV=production PORT=xxxxx`

Since babel-node isn't supposed to run in production, how do you transpile the ES6 in the server.js then?

**Comment by jabhishek** [comment]
Personally I am not a big fan of using babel-node. 
One way to run this in production is to use babel to transpile server.js into another file, say compiled.js and run 
<code>SET NODE_ENV=production && node compiled.js</code>. 

@christianalfoni, what's your take on this?

**Comment by christianalfoni** [comment]
If you check out this project: https://github.com/cerebral/cerebral-website, it is using a setup for this. Not perfectly happy with it, but yeah, one approach :)

**Comment by kulakowka** [comment]
I use babel with `NODE_ENV=production node -r babel-register server.js` for es6 syntax.

**Comment by christianalfoni** [comment]
Is that recommended for production?

**Comment by kulakowka** [comment]
@christianalfoni why not? It is not recommended to use a command-line utility `babel-node` for production. But `babel-register` mode is great for production. 

Other way, you can use `./node_modules/.bin/babel src -d build -D` for build es6 to es5. This is best way for production because in that case you get a fully compiled version in a separate folder. 

In some of my projects I use these scripts in package.json

``` javascript
"scripts": {
      "build": "rm -rf build && ./node_modules/.bin/babel src -d build -D",
      "start": "./node_modules/.bin/babel-node src",
}
```

This makes it possible to execute commands in the console:
`npm start` - for development
`npm run build` - for compile to production.

**Comment by kulakowka** [comment]
In my experience, it is best to deploy and running in production server used [pm2](http://pm2.keymetrics.io/).

**Comment by christianalfoni** [comment]
Cool! Thanks for your input :-)

**Comment by kulakowka** [comment]
@christianalfoni I have used your project for the creation of my starter kit.
It's open for all: https://github.com/kulakowka/react-starter-kit

I added [compression](https://www.npmjs.com/package/compression) to express - it is possible to reduce the size of the bundle ~ 30 kilobytes. I also added a [stylus](http://stylus-lang.com/) for styles. And I made a few other beneficial changes. 

Perhaps you will find something useful for yourself.

**Comment by kulakowka** [comment]
@christianalfoni Thank you for your configuration. it really helped me to create my own webpack config for my needs.

**Comment by christianalfoni** [comment]
:+1:

**Comment by henrikra** [comment]
When I try to run my compiled main.js file I will get error "window is not defined". I used build script to compile.

**Comment by christianalfoni** [comment]
Are you referencing window in your code somewhere?

**Comment by ColeMurray** [comment]
Also getting issues when running `npm run build`
`node dist/main-a133e7dc29e9beb71d65.min.js
/Users/User/Debug/webpack-express-boilerplate/dist/main-a133e7dc29e9beb71d65.min.js:16
function r(e,t){if(!a.canUseDOM||t&&!("addEventListener"in document))return!1;var n="on"+e,r=n in document;if(!r){var i=document.createElement("div");i.setAttribute(n,"return;"),r="function"==typeof i[n]}return!r&&o&&"wheel"===e&&(r=document.implementation.hasFeature("Events.wheel","3.0")),r}var o,a=n(4);a.canUseDOM&&(o=document.implementation&&document.implementation.hasFeature&&document.implementation.hasFeature("","")!==!0),e.exports=r},function(e,t,n){"use strict";var r=n(4),o=n(30),a=n(31),i=function(e,t){e.textContent=t};r.canUseDOM&&("textContent"in document.documentElement||(i=function(e,t){a(e,o(t))})),e.exports=i},function(e,t){"use strict";function n(e,t){var n=null===e||e===!1,r=null===t||t===!1;if(n||r)return n===r;var o=typeof e,a=typeof t;return"string"===o||"number"===o?"string"===a||"number"===a:"object"===a&&e.type===t.type&&e.key===t.key}e.exports=n},function(e,t,n){"use strict";function r(e){return v[e

ReferenceError: document is not defined
    at Object.e.exports.app (/Users/User/Debug/webpack-express-boilerplate/dist/main-a133e7dc29e9beb71d65.min.js:16:30456)
    at t (/Users/User/Debug/webpack-express-boilerplate/dist/main-a133e7dc29e9beb71d65.min.js:1:169)
    at Object.<anonymous> (/Users/User/Debug/webpack-express-boilerplate/dist/main-a133e7dc29e9beb71d65.min.js:1:290)
    at t (/Users/User/Debug/webpack-express-boilerplate/dist/main-a133e7dc29e9beb71d65.min.js:1:169)
    at /Users/User/Debug/webpack-express-boilerplate/dist/main-a133e7dc29e9beb71d65.min.js:1:257
    at Object.<anonymous> (/Users/User/Debug/webpack-express-boilerplate/dist/main-a133e7dc29e9beb71d65.min.js:1:262)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)`

**Comment by ColeMurray** [comment]
@henrikra Are you running `node main-[hash].js?` (This is invalid)

`npm run build` compiles / minifies your client code into the dist directory. It is utilized when running
`NODE_ENV=production PORT=8080 node server.js` (server.js will also need to be transpiled if written in es6)

**Comment by christianalfoni** [comment]
Closing this, please reopen if necessary :)
