### ISSUE TITLE
Clear instructions needed

### ISSUE THREAD

**Issue by taylorsmithgg** [christianalfoni/webpack-express-boilerplate#28]
It took me almost 15 minutes (mostly reading your tutorial) to figure out how exactly you were intending to run the development server. I highly recommend that you put a short, simple solution in your readme.

**Comment by christianalfoni** [comment]
Well, I have spent a lot of hours getting to this point with the boilerplate, so compared to your 15 minutes I would still say that is still a success ;-) It would be really great if you created a pull request with the steps you took to get it working, I am not sure where it got confusing

**Comment by vladinator1000** [comment]
Hey guys, noob here. It took a bit of time for me, but looks clear and understandable, more readme info would cut that down to 5 min :P Sorry for the stupid question, but can I replace the server.js with something like [this](https://github.com/sahat/hackathon-starter) and serve the front end "app" in the public folder?

**Comment by mikeerickson** [comment]
@christianalfoni appreciate your efforts! It always amazes me how demanding users can be for FREE software.  

And for the record, it was pretty straight forward to me :)

**Comment by christianalfoni** [comment]
@mikeerickson Hehe, thanks for the support ;-)

@savovs That should be possible yes, though there are certain dependencies inside the current `server.js` files that needs to be included in the other thing there. Look at the two middlewares in `server.js` that points to webpack. Those needs to be there :)
