### ISSUE TITLE
babel-node to start production server ok ?

### ISSUE THREAD

**Issue by tim-field** [christianalfoni/webpack-express-boilerplate#30]
I noticed that babel-node recommends against its use in production.  Do you think this is something we should worry about ?

https://babeljs.io/docs/usage/cli/#babel-node

https://github.com/christianalfoni/webpack-express-boilerplate/blob/master/package.json#L23

**Comment by christianalfoni** [comment]
Yeah, I would suggest packaging your server using a build script for production. Just create a webpack config for it and an npm script that runs webpack with the config, pointing to your server file. Then use that in production :)
