### ISSUE TITLE
can't get live reload to work

### ISSUE THREAD

**Issue by bgrayburn** [christianalfoni/webpack-express-boilerplate#34]
Hey Christian, I've been starting the server with `sudo npm start` but this doesn't seem to include live reloading. Is it me? Thanks for this awesome boilerplate! Definitely a great way to get something going fast.

**Comment by christianalfoni** [comment]
Hm, that sounds strange @bgrayburn . What file you changing? If it is a react component it uses hot reloading, which means no refresh, it just updates the content right there. Like css hot loading :)

**Comment by bgrayburn** [comment]
@christianalfoni thanks for getting back to me, I was changing a React Component file, but the change wasn't showing up in the browser, nor was css hot loading working, it's cool I need to dig in more to the webpack process and figure it out

**Comment by christianalfoni** [comment]
You have the .babelrc file? That is where the hot reloading is defined, though CSS should work. I have moved the configuration to the config now, as ZIP files do not contain . files :)

Repoen if it still does not work
