### ISSUE TITLE
How I can add livereload to the server?

### ISSUE THREAD

**Issue by armandomendivil** [christianalfoni/webpack-express-boilerplate#35]

**Comment by jaredpalmer** [comment]
This is an outstanding issue in the webpack universe... There isn't a great way to do it yet. 

jlongster has an interesting technique: https://github.com/jlongster/blog

More discussion:
webpack/docs#45
gaearon/react-hot-loader#113

**Comment by christianalfoni** [comment]
There is a way! :-)

Check out the kotatsu project. Really great stuff! Its not only live-reloading, but hot-reloading. https://github.com/Yomguithereal/kotatsu
