### ISSUE TITLE
Unexpected Token < ... bundle.js

### ISSUE THREAD

**Issue by NigelEarle** [christianalfoni/webpack-express-boilerplate#70]
Everything seems to be working great! Just getting a single error...

![screen shot 2017-02-09 at 10 35 05 am](https://cloud.githubusercontent.com/assets/6581633/22802082/89ce705c-eeb3-11e6-9811-80687b7804e7.png)

And when I open it up, the console tells me...

![screen shot 2017-02-09 at 10 36 54 am](https://cloud.githubusercontent.com/assets/6581633/22802136/c695012c-eeb3-11e6-9407-4b3ab9a053a7.png)

Has anyone ran into this error before? Thanks!

**Comment by NigelEarle** [comment]
Ah got it. Had to remove the `script` tag in my index.html file, manually referencing my bundle at `/build/bundle.js`. `HtmlWebpackPlugin()` inserts the script tag in the body in reference to the bundle. The more you know...lol

**Comment by YuliBlanco** [comment]
Hi! I have the same problem 

this is my code 

<!doctype html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>Reduxstagram</title>
    <link rel="shortcut icon" type="image/png" href="http://wes.io/ehRe/my-favourite-icon.png"/>

  </head>
  <body>
    <div id="root"></div>
    <script src="/static/bundle.js"></script>
  </body>
</html>

and the reduxstagram.js here

import React from 'react';
import {render} from 'react-dom';
import css from './styles/style.css'


 
render (<p>prueba</p>, document.getElementById('root'));

if you can helpme; textme please!
