### ISSUE TITLE
Cannot resolve module 'prop-types' redbox

### ISSUE THREAD

**Issue by myk5000** [christianalfoni/webpack-express-boilerplate#74]
FYI, downloaded boilerplate, npm install, npm start - 

`ERROR in ./~/redbox-react/lib/index.js
Module not found: Error: Cannot resolve module 'prop-types' in C:\<path>\node_modules\redbox-react\lib
 @ ./~/redbox-react/lib/index.js 12:17-38
`

**Comment by christianalfoni** [comment]
@myk5000 This is React 16 change, it needs an extra dependency :-)

**Comment by JesseDobson** [comment]
+christianalfoni what is that extra dependency and do i specify it in package.json?

**Comment by cdosborn** [comment]
No need to add an extra dependency. Read the [press-release](https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html#migrating-from-react.proptypes) from React.
