### ISSUE TITLE
Error: ENOENT, stat dist/index.html

### ISSUE THREAD

**Issue by Guria** [christianalfoni/webpack-express-boilerplate#8]
Sometimes console logs out `Error: ENOENT, stat '/home/ubuntu/workspace/dist/index.html'`

**Comment by brandondurham** [comment]
Having the same issue.

**Comment by risto1913** [comment]
Same issue here.

Love the Boilerplate. Thanx

**Comment by leomelin** [comment]
You should propably run "webpack" once in project directory to create dist/index.html

**Comment by jenil** [comment]
Has anyone figured this out?

**Comment by the-watchmaker** [comment]
Hello? Anybody?

**Comment by leomelin** [comment]
1. in project directory run "webpack" to generate /dist/ directory with files
2. change output filename in webpack config file to "bundle.js" instead of "[name].js", like this:

```
output: {
    path: path.join(__dirname, '/dist/'),
    filename: 'bundle.js',
    publicPath: '/'
  }
```
1. npm start and it should work

**Comment by jenil** [comment]
:+1: yes, just run a `webpack` to create the files in the dist/ and then you should be good to go.

**Comment by leomelin** [comment]
@jgog I noticed that at least for me, I had to change the webpack config filename too for hot loading to work - just running `webpack` made the ENOENT error message to disappear but made further changes to files not to hotload. Did you notice anything similar?

**Comment by jenil** [comment]
I left the config as it is, ran `webpack` and then ran `npm run start` but with that the reloading did not work. So I went into the dist/ and deleted the main.js and the reloading also started to work.

**Comment by christianalfoni** [comment]
Hi guys,

What is the status here now? Should we change something in the boilerplate to avoid this confusion? I have not met the issue myself.

**Comment by jenil** [comment]
I don't think any change is required in the boilerplate.

**Comment by christianalfoni** [comment]
cool :-)
