### ISSUE TITLE
what the fuck asshole

### ISSUE THREAD

**Issue by ghost** [christianalfoni/webpack-express-boilerplate#82]
this doesnt fucking work!

**Comment by clarkeash** [comment]
It sucks that it doesn’t work for you, if you need help then provide some information as to why it doesn’t work.

This package is maintained by someone in their spare time and provided to the community for free, so let’s be nice to them.

**Comment by christianalfoni** [comment]
Yeah, you seriously need to read up on open source @mooresvilleinnovationlab...
